### PR TITLE
Deprecate PySOA

### PR DESCRIPTION
**Pull request by eyalr**

### CODE REVIEW

**Comment by vellis-eb** [comment]
Since PySOA is a public repo, we need management approval in order to change the status to deprecated.

**Comment by jcfant-eb** [comment]
What do we believe next steps for this are?

**Review by danpinkard-eb — APPROVED** [review]

**Comment by eldalai** [comment]
LGTM :)

**Review by eldalai — APPROVED** [review]

**Comment by dcaliri** [comment]
LGTM

**Pull request merged**
